model:
  type: 'YOLO'
  background: False
  backbone:
    type: 'TinyYOLOv3'
    freeze: 0
  anchors: [[10, 14], [23, 27], [37, 58], [81, 82], [135, 169], [344, 319]]
  anchors_mask: [[3, 4, 5], [0, 1, 2]]
  head:
    type: 'TinyYOLOv3ASPP'
    in_channels: [256, 256]
    num_anchors: [3, 3]

train:
  gpus: "6"
  nworkers: 6
  pin_mem: True

  clear: False

  optimizer:
    base_lr: 0.001
    bias_lr_factor: 2
    momentum: 0.9
    weight_decay: 0.0005
    bias_weight_decay: 0

  scheduler:
    type: "steps"
#    type: "cos"
    warmup_iters: 400
    warmup_factor: 0.1
    warmup_method: "linear"
#    eta_min: 0.00001
    gamma: 0.1
    milestones: [4000, 6000]

  max_batches: 7200
  resize_interval: 0

  backup_interval: 20
  backup_steps: [1000]
  backup_rates: [10000]
  backup_dir: "backup/"

  input_size: [416, 416]
  batch_size: 64
  mini_batch_size: 4
  weights: "weights/TinyYOLOv3.features"

test:
  gpus: "3"
  nworkers: 1
  pin_mem: True

  input_size: [416, 416]
  batch_size: 1
  weights: "weights/TinyYOLOv3_LAB_fine.pth"

  conf_thresh: 0.05
  nms_thresh: 0.4
  ignore_thresh: 0.5
  num_detect: 100

  results: "results"
