all:
	cd nms/ && python setup.py build_ext --inplace && rm -rf build/
	cd roi_align/ && python setup.py build_ext --inplace && rm -rf build/
	cd roi_pool/ && python setup.py build_ext --inplace && rm -rf build/
	cd sigmoid_focal_loss/ && python setup.py build_ext --inplace && rm -rf build/
